/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.id.itb.tgs2.znake.view;

import ac.id.itb.tgs2.znake.ZnakeConstants;
import ac.id.itb.tgs2.znake.command.*;
import ac.id.itb.tgs2.znake.controller.ZnakeController;
import ac.id.itb.tgs2.znake.model.Znake;
import ac.id.itb.tgs2.znake.model.ZnakeBodyPart;
import info.clearthought.layout.TableLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.SwingWorker;

/**
 *
 * @author edbert
 */
public class ZnakeView extends javax.swing.JFrame {

    private ZnakeController engine;
    private KeyAdapter keyAdapter;

    /**
     * Creates new form ZnakeView
     */
    public ZnakeView() {
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 388, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void initializeComponents() {
        engine = new ZnakeController();

        keyAdapter = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                ZnakeCommand cmd;
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_UP:
                        cmd = new MoveUpCommand(engine.getZnakeOperation());
                        break;
                    case KeyEvent.VK_RIGHT:
                        cmd = new MoveRightCommand(engine.getZnakeOperation());
                        break;
                    case KeyEvent.VK_DOWN:
                        cmd = new MoveDownCommand(engine.getZnakeOperation());
                        break;
                    case KeyEvent.VK_LEFT:
                        cmd = new MoveLeftCommand(engine.getZnakeOperation());
                        break;
                    default:
                        cmd = new MoveCommand(engine.getZnakeOperation());
                }
                cmd.execute();
            }
        };
        addKeyListener(keyAdapter);
        
        this.add(engine.getPanel());
        
        engine.run();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
